# dados.py

reviews = ["Rápido e útil!",
"Fácil de usar e informativo.",
"Algumas respostas genéricas.",
"Confuso no início, mas útil depois.",
"Não conseguiu resolver meu problema.",
"Bom para consultas simples.",
"Interface intuitiva.",
"Respostas pré-programadas.",
"Impressionado com a precisão.",
"Precisa de atualizações.",
"Eficiente e direto ao ponto.",
"Interativo e informativo.",
"Poderia ser mais personalizado.",
"Atendeu minhas expectativas.",
"Precisa de melhorias na compreensão.",
"Boa experiência no geral.",
"Facilitou minha busca.",
"Poderia ser mais agradável.",
"Ajudou, mas pode ser mais preciso.",
"Funcionalidades limitadas.",
"Satisfatório, mas não excepcional.",
"Melhor do que eu esperava.",
"Útil em momentos de necessidade.",
"Poderia ter mais opções de suporte.",
"Agradável de usar, mas não surpreendente.",
"Boa tentativa, mas precisa de refinamento.",
"Simplificou minha consulta.",
"Boa resposta às consultas básicas.",
"Esperava mais interatividade.",
"Poderia ser mais proativo.",
"Incansável e eficiente!",
"Um pouco genérico, mas útil.",
"Falhou no meu problema específico.",
"Básico demais para desafios.",
"Faltou a humanidade.",
"Preciso como um raio laser!",
"Hora de uma atualização, não acha?",
"Complicado, porém útil.",
"Frustrante e limitado.",
"Simples demais.",
"Eficiente e claro.",
"Funciona bem.",
"Ok, poderia ser melhor.",
"Mediano, mas resolve.",
"Muito automático.",
"Um ajudante prestativo!",
"Como um guia turístico inexperiente.",
"Fácil de usar, mas não encanta.",
"Um assistente virtual obediente.",
"Um fiel amigo digital.",
"Como um dicionário: útil, mas sem emoção.",
"Um colega de trabalho competente.",
"Tão previsível quanto o nascer do sol.",
"Suficiente, mas não excepcional.",
"Um guia turístico digital comum.",
"Como uma lanterna na escuridão digital.",
"Tão animado quanto um código de barras.",
"Como um mapa antigo: útil, mas desatualizado.",
"Como um farol de luz na névoa da informação.",
"Direto ao ponto, mas meio sem sal.",
"Funciona, mas falta aquele tchã.",
"Tipo, meio robótico, sabe?",
"Como um amigo chato, mas útil.",
"Responde, mas sem aquele jeitão de gente.",
"Básico, mas não tão cativante.",
"Como um papo com o professor: meio seco.",
"Responde, mas sem dar aquele algo a mais.",
"Funciona, mas sem aquela vibe.",
"Poderia ser mais descolado, menos quadradão.",
"Funciona, mas sem aquela pegada.",
"Como um colega meio entediante.",
"Ok, mas falta aquele brilho nos olhos.",
"Responde, mas sem emoção.",
"Básico demais, nada emocionante.",
"Como um papo com o tiozão na fila do banco.",
"Tá lá, mas sem aquela animação.",
"Como aquele amigo que sempre responde blz nas mensagens.",
"Atende bem, sabe? Tipo, resolve na hora.",
"Funciona direitinho, até dá pra trocar umas ideias.",
"Responde rápido e sem enrolação, top!",
"É como ter um assistente pessoal, mas digital, saca?",
"Bate o maior papo e ainda te dá as infos certas, show!",
"Simplesmente resolve, sem fazer drama, beleza total.",
"É aquele parceiro que nunca te deixa na mão, nota 10!",
"Soluções prontas e precisas.",
"Demonstra utilidade imediata.",
"Rápido e pertinente.",
"Confiança e eficiência.",
"Ágil e preciso.",
"Prontidão e eficácia.",
"Demonstra notável diligência e eficácia.",
"Exibe presteza excepcional e pertinência.",
"Destaca-se por celeridade e eficácia.",
"Demonstra rápida prontidão e precisão.",
"Destaca-se por presteza e eficácia.",
"Apresenta respostas inconsistentes e pouco confiáveis.",
"Demonstra uma falta de precisão e eficiência.",
"Exibe uma lentidão preocupante na entrega de soluções.",
"Provê respostas pouco úteis e desatualizadas.",
"Destaca-se por sua ineficácia e falta de pertinência.",
"Apresenta-se como um recurso pouco confiável e impreciso.",
"Demonstra uma falha evidente na entrega de soluções adequadas.",
"Exibe uma falta de prontidão e eficácia preocupante.",
"Provê respostas tardias e inadequadas.",
"Rápido e preciso! Adorei.",
"Muito útil, resolveu meu problema rapidamente!",
"Interface amigável e respostas informativas.",
"Excelente experiência de usuário, obrigado!",
"Sempre confiável e eficiente, recomendo.",
"Adoro a rapidez das respostas, muito eficiente.",
"Simples de usar e muito útil, excelente trabalho!",
"Surpreendentemente útil, realmente me impressionou.",
"Meu assistente favorito, sempre me ajuda quando preciso.",
"Sempre atento às minhas necessidades, muito grato.",
"Confuso e pouco útil, não consegui resolver meu problema.",
"Respostas genéricas e pouco informativas, decepcionante.",
"Interface complicada e respostas pouco úteis.",
"Frustrante de usar, não consegui encontrar o que precisava.",
"Muito lento para responder, não vale a pena.",
"Pouco confiável e inconsistente, não recomendo.",
"Não atendeu minhas expectativas, muito decepcionado.",
"Precisa de melhorias urgentes, está abaixo do padrão.",
"Não consegui obter respostas claras, muito insatisfeito.",
"Falhou em fornecer as informações corretas, muito frustrante.",
"Rápido e eficaz, ótimo!",
"Muito útil, adorei!",
"Simples e eficiente, perfeito!",
"Impressionante, resolveu rápido!",
"Interface intuitiva, excelente!",
"Preciso e direto, top!",
"Eficiente e amigável, recomendo!",
"Sempre confiável, obrigado!",
"Ótima ajuda, muito grato!",
"Satisfeito com o serviço, obrigado!",
"Confuso e lento, decepcionante.",
"Pouco útil, frustrante.",
"Complicado e ineficaz, péssimo.",
"Desapontado, não resolveu.",
"Interface confusa, não recomendo.",
"Inconsistente e irritante, evite.",
"Insatisfatório, não atendeu.",
"Precisa de melhorias urgentes, fraco.",
"Frustrado com as respostas, péssimo.",
"Não confiável, muito decepcionante.",
"Uau, me senti compreendido pelo chatbot!",
"É como ter um amigo sempre pronto para ajudar!",
"Amei a interação, me senti bem-vindo!",
"Impressionado com o cuidado e atenção aos detalhes.",
"Caramba, o chatbot realmente se importa comigo!",
"Senti uma conexão genuína, muito obrigado!",
"Não sei como teria sobrevivido sem esse suporte maravilhoso.",
"Sabe, o chatbot é tipo meu confidente virtual!",
"Me fez sentir especial, como se fosse só para mim.",
"Obrigado por estar sempre lá quando mais preciso, chatbot!",
"Me sinto ignorado e incompreendido pelo chatbot.",
"Frustrado com a falta de empatia e compreensão.",
"É como conversar com uma parede, totalmente inútil.",
"Não sei se o chatbot me escuta ou apenas responde automaticamente.",
"Sinto que minhas perguntas são ignoradas ou mal interpretadas.",
"Desapontado com a falta de humanidade nas respostas.",
"É como se o chatbot não se importasse comigo de verdade.",
"Me faz sentir como se eu fosse apenas mais um número.",
"Às vezes me sinto completamente perdido ao interagir com o chatbot.",
"Cansado da superficialidade das respostas, não me ajuda em nada.",
"O chatbot é incrível, sempre útil!",
"Simplesmente adoro o chatbot!",
"Fantástico, o chatbot resolve tudo!",
"Impressionante, sempre eficaz!",
"O melhor suporte que já tive!",
"Sempre surpreendente, obrigado!",
"Muito útil, não vivo sem!",
"Excelente, sempre me ajuda!",
"Sensacional, não tenho palavras!",
"Fascinante, não poderia ser melhor!",
"Eficiente e rápido, resolve tudo!",
"Surpreendente, sempre me ajuda!",
"Incrível, nunca falha em me entender!",
"Excelente suporte, nunca me deixa na mão!",
"Fantástico, simplifica minha vida!",
"Maravilhoso, sempre à disposição!",
"Impressionante, resolve tudo com facilidade!",
"Ótimo serviço, super prático!",
"Excepcional, sempre acerta em cheio!",
"Brilhante, super inteligente e eficaz!",
"Frustrante, não entende minhas perguntas!",
"Confuso e inútil, não resolve nada!",
"Desapontador, não atende minhas expectativas!",
"Irritante, só complica as coisas!",
"Ineficiente, não ajuda em nada!",
"Decepcionante, não serve para nada!",
"Lamentável, não faz diferença!",
"Desastroso, só causa mais problemas!",
"Perdido, não sabe o que está fazendo!",
"Genérico e inútil, não recomendo!",
"Veloz e eficaz, sempre resolve!",
"Sensacional, nunca me deixa na mão!",
"Espetacular, facilita minha vida!",
"Top, sempre acerta em cheio!",
"Firmeza total, confiável demais!",
"Arrasa, sempre presente quando preciso!",
"Nota 10, nunca decepciona!",
"Fantástico, um verdadeiro salva-vidas!",
"Fera demais, simplifica tudo!",
"Mito, supera minhas expectativas sempre!",
"Um tanto confuso, às vezes piora!",
"Meio perdido, não sabe o que faz!",
"Desanimador, não resolve direito!",
"Intrigante, mais atrapalha que ajuda!",
"Deixa a desejar, não acompanha!",
"Insatisfatório, pouco eficiente!",
"Desnorteante, não confio muito!",
"Decepcionante, não cumpre o prometido!",
"Complicado demais, não entende!",
"Falta aquele algo, não convence!",
"Rápido e certeiro, sempre impressiona!",
"Surpreendente, nunca falha em me ajudar!",
"Show de bola, resolve tudo com maestria!",
"Nota mil, não sei o que seria de mim sem ele!",
"Brilhante, simplifica minha vida em segundos!",
"Impecável, um verdadeiro expert no que faz!",
"Estrela do show, sempre no ponto certo!",
"Top das galáxias, não há desafio que ele não supere!",
"Mágico, transforma problemas em soluções em um piscar de olhos!",
"Fenomenal, um aliado indispensável em todas as situações!",
"Confuso e desorientado, mais atrapalha do que ajuda!",
"Desconcertante, nunca sabe por onde começar!",
"Desapontador, não faz jus às expectativas!",
"Desafiador, parece ter vida própria!",
"Intrigante, suas respostas deixam a desejar!",
"Desgastante, mais um obstáculo do que uma solução!",
"Frustrante, sua ineficácia é de cortar o coração!",
"Desconcertante, parece ter vontade própria!",
"Desmotivador, não é tão útil quanto promete ser!",
"Desencorajador, esperava mais dele!",
"Eficiente e confiável, sempre pronto para ajudar!",
"Brilhante em sua simplicidade, uma verdadeira maravilha!",
"Eficaz e rápido, uma bênção em momentos de necessidade!",
"Preciso e ágil, uma verdadeira jóia da tecnologia!",
"Útil e rápido, um verdadeiro salva-vidas virtual!",
"Eu gostei.",
"Não está ruim.",
"Ajudou bastante.",
"Para mim, foi uma boa experiência,",
"Achei interessante.",
"Confuso e frustrante, mais problema do que solução.",
"Desorientador e impreciso, difícil de confiar.",
"Lento e complicado, mais atrapalha do que ajuda.",
"Ineficaz e confuso, não cumpre o prometido.",
"Irrelevante e confuso, não vale a pena o esforço.",
"Não ajuda muito.",
"Me deixou confuso.",
"Eu não gostei.",
"Passa longe de ser bom.",
"Está bem ruim, precisa melhorar muito.",
"Responde rápido e com precisão.",
"Simples de usar e eficiente.",
"Sempre útil em momentos cruciais.",
"Claro e direto ao ponto.",
"Impressiona com sua eficácia.",
"Sempre disponível quando necessário.",
"Confiança total em suas respostas.",
"Rápido e eficiente em suas soluções.",
"Sabe exatamente o que fazer.",
"Facilita minha vida em segundos.",
"Confuso e pouco útil.",
"Lento e cheio de falhas.",
"Complica mais do que resolve.",
"Inconsistente e frustrante.",
"Não confiável em suas respostas.",
"Difícil de entender e seguir.",
"Não atende às expectativas.",
"Desajeitado e pouco prático.",
"Não entrega o que promete.",
"Deixa muito a desejar em termos de utilidade.",
"Eu confio nele para resolver meus problemas.",
"Me surpreende com sua rapidez.",
"Ele sempre me ajuda quando estou perdido.",
"Me economiza tempo e esforço.",
"Eu me sinto seguro usando suas respostas.",
"Ele é simples e eficaz.",
"Eu o vejo como meu aliado digital.",
"Ele sabe exatamente o que eu preciso.",
"Me tranquiliza saber que está disponível.",
"Ele é essencial para mim.",
"Ele me deixa frustrado com suas respostas confusas.",
"Me irrita com sua lentidão.",
"Suas soluções muitas vezes me deixam desanimado.",
"Me confunde com respostas imprecisas.",
"Não confio nele para resolver meus problemas.",
"Ele me deixa perplexo com suas falhas.",
"Me decepciona com sua falta de utilidade.",
"Me deixa confuso e insatisfeito.",
"Me desencoraja quando não entrega o prometido.",
"Me faz questionar sua eficácia e relevância.",
"Me surpreendeu.",
"Eu adorei.",
"Me impressionou.",
"Eu recomendo.",
"Achei legal.",
"Me encantou.",
"Eu amei.",
"Me conquistou.",
"Eu me apaixonei.",
"Me cativou.",
"Me decepcionou.",
"Eu esperava mais.",
"Não gostei.",
"Me desapontou.",
"Eu esperava melhor.",
"Me desagradou.",
"Eu me arrependi.",
"Não me convenceu.",
"Me desiludiu.",
"Eu esperava mais dele.",
"Adorei! Muito útil!",
"Excelente! Resolveu meu problema rapidinho.",
"Top! Recomendo a todos.",
"Maravilhoso! Me salvou tempo.",
"Ótimo serviço! Super fácil de usar.",
"Simplesmente incrível! Funcionou perfeitamente.",
"Fantástico! Não poderia ser melhor.",
"Amei! Nunca mais fico sem.",
"Muito bom! Vou usar sempre.",
"Perfeito! Nota 10!",
"Péssimo! Não resolveu nada.",
"Terrível! Perdi meu tempo.",
"Horrível! Não recomendo a ninguém.",
"Uma porcaria! Não funcionou como esperado.",
"Desastroso! Só me deu dor de cabeça.",
"Inútil! Não serve para nada.",
"Frustrante! Esperava mais.",
"Decepcionante! Não cumpriu o prometido.",
"Ruim demais! Precisa melhorar muito.",
"Insatisfatório! Não atendeu minhas expectativas.",
"Top!",
"Show!",
"Mara!",
"Massa!",
"Genial!",
"Legal.",
"Incrível!",
"Arrasou!",
"Amei!",
"Perfeito!",
"Ruim.",
"Péssimo.",
"Decepcionante.",
"Horroroso.",
"Desastroso.",
"Furada.",
"Triste.",
"Bosta.",
"Desapontador.",
"Desperdício.",
"É incrivelmente útil para responder rapidamente às minhas perguntas.",
"Está sempre disponível, o que é conveniente para mim.",
"Para mim, é como ter um assistente pessoal sempre à disposição.",
"Eu aprecio a sua capacidade de compreender contextos complexos.",
"Acho que sua interface é intuitiva e fácil de usar.",
"É muito bom em fornecer informações precisas e relevantes.",
"Está sempre melhorando, o que mostra dedicação à qualidade.",
"Para mim, é uma ferramenta essencial para o meu trabalho.",
"Eu me sinto mais produtivo desde que comecei a usá-lo.",
"Acho que sua personalidade amigável torna a interação mais agradável.",
"É frustrante quando não consegue entender o que estou perguntando.",
"Está muito limitado em termos de tópicos que pode discutir.",
"Para mim, às vezes parece mais um robô do que um assistente genuíno.",
"Eu gostaria que fosse mais rápido em suas respostas.",
"Acho que sua base de conhecimento é um pouco superficial.",
"É irritante quando repete informações que já sei.",
"Está claro que ainda tem dificuldade em lidar com nuances na linguagem.",
"Para mim, sua personalidade parece artificial e forçada.",
"Eu esperava mais opções de personalização para atender às minhas necessidades específicas.",
"Acho que sua falta de empatia pode tornar a interação desagradável em certas situações.",
"É rápido e útil.",
"Sempre disponível.",
"Útil como assistente.",
"Interface intuitiva.",
"Preciso e relevante.",
"Melhorando constantemente.",
"Ferramenta essencial.",
"Aumenta minha produtividade.",
"Interativo e amigável.",
"Informações úteis e claras.",
"Às vezes não compreende.",
"Limitado em tópicos.",
"Parece artificial.",
"Respostas lentas.",
"Conhecimento superficial.",
"Repetitivo.",
"Dificuldade com nuances.",
"Personalidade forçada.",
"Pouca personalização.",
"Falta de empatia.",
"Não é ruim.",
"Poderia ser pior.",
"Ainda é útil.",
"Não decepciona.",
"Não é perfeito, mas ainda é uma ferramenta valiosa.",
"Não é tão ruim.",
"Serve bem.",
"Não deixa a desejar.",
"Ajuda bastante.",
"Para mim, está bom.",
"Poderia ser muito melhor em captar nuances na linguagem.",
"Não agrada totalmente devido à sua falta de personalidade.",
"Não é tão perfeito quanto esperava.",
"Não é extraordinário.",
"Não é excepcional.",
"Não é bom.",
"É ruim.",
"Não serve.",
"Não ajuda.",
"Fraco.",
"Não é nada mal.",
"Não decepciona.",
"Cumpre com o que promete.",
"Não é de todo ruim.",
"É muito mais do que um robô.",
"Orienta bem.",
"Ajuda bastante.",
"Auxilia muito.",
"É absurdo de bom.",
"É muito bom.",
"Não fede nem cheira.",
"Decepciona.",
"Não cumpre com o que promete.",
"Não é nada bom.",
"Não passa de um robô.",
"Orienta mal.",
"Ajuda pouco.",
"Não auxilia nada.",
"É absurdo de ruim",
"É muito ruim.",
"Não está nada mal.",
"Não deixa a desejar.",
"Atende às expectativas.",
"Não é ruim.",
"É surpreendentemente bom.",
"Tem sido útil.",
"Faz um bom trabalho.",
"Muito mais do que um programa comum.",
"Melhor do que eu esperava.",
"É bastante competente.",
"Está bem mal.",
"Deixa a desejar.",
"Não tende às expectativas.",
"É ruim.",
"É surpreendentemente ruim.",
"Tem sido inútil.",
"Não faz um bom trabalho.",
"Não passa de um programa comum.",
"Pior do que eu esperava.",
"É pouco competente.",
"Não está nada mal mesmo.",
"Está satisfatório.",
"Faz o que é necessário.",
"Serve ao propósito.",
"Não é ruim de todo.",
"Atende às demandas.",
"Faz o trabalho direito.",
"Supera as expectativas mínimas.",
"Tem sido uma boa adição.",
"Tem sido útil até agora.",
"Está bem mal mesmo.",
"Está insatisfatório.",
"Não faz o que é necessário.",
"Não serve ao propósito.",
"É ruim de todo.",
"Não atende às demandas.",
"Faz o trabalho todo errado.",
"Não supera as expectativas mínimas.",
"Tem sido uma adição ruim.",
"Não tem sido útil até agora.",
"Surpreendentemente útil! Superou minhas expectativas.",
"Embora básico, ainda é bastante funcional.",
"Não é excepcional, mas faz o trabalho de forma satisfatória.",
"Não é o melhor, mas ainda é melhor do que nada.",
"Não tão impressionante quanto outros, mas ainda é uma opção viável.",
"Não é perfeito, mas ainda é uma ferramenta útil para referência rápida.",
"Confuso no início, mas útil com o tempo.",
"Eficiente para consultas rápidas.",
"Útil em momentos de necessidade.",
"Boa opção para tarefas simples.",
"Funciona, mas não tem o brilho que eu esperava.",
"Rápido e informativo, mas falta personalidade.",
"Interface intuitiva, mas respostas pré-programadas.",
"Atendeu minhas expectativas básicas, mas carece de emoção.",
"Satisfatório, mas não excepcional.",
"Funciona bem, mas precisa de melhorias.",
"Respostas consistentes, mas genéricas.",
"Interface intuitiva, mas falta profundidade.",
"Funciona, mas pode ser mais preciso.",
"Bom para referência rápida, mas limitado.",
"Rápido e preciso! Adorei.",
"Muito útil, resolveu meu problema rapidamente!",
"Interface amigável e respostas informativas.",
"Excelente experiência de usuário, obrigado!",
"Sempre confiável e eficiente, recomendo.",
"Adoro a rapidez das respostas, muito eficiente.",
"Rápido e eficaz, ótimo!",
"Muito útil, adorei!",
"Simples e eficiente, perfeito!",
"Impressionante, resolveu rápido!",
"Interface intuitiva, excelente!",
"Preciso e direto, top!",
"Eficiente e amigável, recomendo!",
"Sempre confiável, obrigado!",
"Ótima ajuda, muito grato!",
"Satisfeito com o serviço, obrigado!",
"Uau, me senti compreendido pelo chatbot!",
"É como ter um amigo sempre pronto para ajudar!",
"Amei a interação, me senti bem-vindo!",
"Senti uma conexão genuína, muito obrigado!",
"Sabe, o chatbot é tipo meu confidente virtual!",
"Responde rápido e com precisão.",
"Simples de usar e eficiente.",
"Sempre útil em momentos cruciais.",
"Claro e direto ao ponto.",
"Impressiona com sua eficácia.",
"Sempre disponível quando necessário.",
"Confiança total em suas respostas.",
"Rápido e eficiente em suas soluções.",
"Sabe exatamente o que fazer.",
"Facilita minha vida em segundos.",
"Eu confio nele para resolver meus problemas.",
"Me surpreende com sua rapidez.",
"Ele sempre me ajuda quando estou perdido.",
"Me economiza tempo e esforço.",
"Eu me sinto seguro usando suas respostas.",
"Ele é simples e eficaz.",
"Eu o vejo como meu aliado digital.",
"Ele sabe exatamente o que eu preciso.",
"Me tranquiliza saber que está disponível.",
"Ele é essencial para mim.",
"Eu adorei.",
"Me impressionou.",
"Eu recomendo.",
"Achei legal.",
"Me encantou.",
"Eu amei.",
"Me conquistou.",
"Eu me apaixonei.",
"Me cativou.",
"Confuso e pouco útil, não consegui resolver meu problema.",
"Respostas genéricas e pouco informativas, decepcionante.",
"Interface complicada e respostas pouco úteis.",
"Frustrante de usar, não consegui encontrar o que precisava.",
"Muito lento para responder, não vale a pena.",
"Pouco confiável e inconsistente, não recomendo.",
"Não atendeu minhas expectativas, muito decepcionado.",
"Precisa de melhorias urgentes, está abaixo do padrão.",
"Não consegui obter respostas claras, muito insatisfeito.",
"Falhou em fornecer as informações corretas, muito frustrante.",
"Me senti ignorado e incompreendido pelo chatbot.",
"Frustrado com a falta de empatia e compreensão.",
"É como conversar com uma parede, totalmente inútil.",
"Não sei se o chatbot me escuta ou apenas responde automaticamente.",
"Sinto que minhas perguntas são ignoradas ou mal interpretadas.",
"Desapontado com a falta de humanidade nas respostas.",
"É como se o chatbot não se importasse comigo de verdade.",
"Me faz sentir como se eu fosse apenas mais um número.",
"Às vezes me sinto completamente perdido ao interagir com o chatbot.",
"Cansado da superficialidade das respostas, não me ajuda em nada.",
"Frustrante, não entende minhas perguntas!",
"Confuso e inútil, não resolve nada!",
"Desapontador, não atende minhas expectativas!",
"Irritante, só complica as coisas!",
"Ineficiente, não ajuda em nada!",
"Decepcionante, não serve para nada!",
"Lamentável, não faz diferença!",
"Desastroso, só causa mais problemas!",
"Perdido, não sabe o que está fazendo!",
"Genérico e inútil, não recomendo!",
"Confuso e desorientado, mais atrapalha do que ajuda!",
"Desconcertante, nunca sabe por onde começar!",
"Desapontador, não faz jus às expectativas!",
"Desafiador, parece ter vida própria!",
"Intrigante, suas respostas deixam a desejar!",
"Desgastante, mais um obstáculo do que uma solução!",
"Frustrante, sua ineficácia é de cortar o coração!",
"Desconcertante, parece ter vontade própria!",
"Desmotivador, não é tão útil quanto promete ser!",
"Desencorajador, esperava mais dele!",
"Não é bom.",
"Terrível.",
"Horrível.",
"Uma porcaria.",
"Desastroso.",
"Furada.",
"Triste.",
"Bosta.",
"Desapontador.",
"Desperdício."]

labels = ["positivo",
"positivo",
"negativo",
"positivo",
"negativo",
"positivo",
"positivo",
"negativo",
"positivo",
"negativo",
"positivo",
"positivo",
"negativo",
"positivo",
"negativo",
"positivo",
"positivo",
"negativo",
"negativo",
"negativo",
"negativo",
"positivo",
"positivo",
"negativo",
"negativo",
"negativo",
"positivo",
"positivo",
"negativo",
"negativo",
"positivo",
"positivo",
"negativo",
"negativo",
"negativo",
"positivo",
"negativo",
"positivo",
"negativo",
"negativo",
"positivo",
"positivo",
"negativo",
"positivo",
"negativo",
"positivo",
"negativo",
"negativo",
"positivo",
"positivo",
"negativo",
"positivo",
"negativo",
"negativo",
"negativo",
"positivo",
"negativo",
"negativo",
"positivo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"positivo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo",
"negativo"]